version: "3.9"

services:
  asterisk:
    image: andrius/asterisk:latest

    container_name: asterisk

    restart: unless-stopped

    ports:
      # SIP
      - "5060:5060/udp"
      - "5060:5060/tcp"

      # ARI
      - "8088:8088"

      # RTP
      - "10000-10100:10000-10100/udp"

    volumes:
      # Конфиги
      - ./asterisk_config/pjsip.conf:/etc/asterisk/pjsip.conf
      - ./asterisk_config/extensions.conf:/etc/asterisk/extensions.conf
      - ./asterisk_config/rtp.conf:/etc/asterisk/rtp.conf
      - ./asterisk_config/http.conf:/etc/asterisk/http.conf
      - ./asterisk_config/ari.conf:/etc/asterisk/ari.conf

      # Логи
      - ./asterisk_log:/var/log/asterisk

    networks:
      - voip-net

  # ======================================================
  # PYTHON AI / RTP
  # ======================================================

  smartvoice:
    build:
      context: ./
    image: smartvoice:latest
    container_name: smart_voice

    restart: unless-stopped

    depends_on:
      - asterisk

    working_dir: /smartvoice

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    
    volumes:
      # LIVE CODE MOUNT
      - ./backend:/smartvoice
      - ./modules/vosk-model-ru-0.42:/smartvoice/modules/vosk-model-ru-0.42

    ports:
      - "8000:8000"


    environment:
      DATABASE_URL: postgresql+asyncpg://smartvoice_admin:1qp21qp2@postgres:5432/smartvoice
      REDIS_URL: redis://redis:6379/0
  
    networks:
      - voip-net
  
  # =======================================================
  # CELERY WORKER
  # =======================================================
  celery-worker:
    image: smartvoice:latest
  
    container_name: celery-worker
    restart: unless-stopped

    depends_on:
      - redis
      - postgres

    command: celery -A app.core.celery worker -l info --concurrency=1

    environment:
      DATABASE_URL: postgresql+asyncpg://smartvoice_admin:1qp21qp2@postgres:5432/smartvoice
      REDIS_URL: redis://redis:6379/0

    ports:
      # optional debug port
      - "6000:6000/udp"

    volumes:
      - ./modules/vosk-model-ru-0.42:/smartvoice/modules/vosk-model-ru-0.42
  
    networks:
      - voip-net

  # ======================================================
  # REDIS
  # ======================================================
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    networks:
      - voip-net

  # =======================================================
  # POSTGRES
  # =======================================================
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: smartvoice
      POSTGRES_USER: smartvoice_admin
      POSTGRES_PASSWORD: 1qp21qp2

    ports:
      - "5433:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

    networks:
      - voip-net
# =========================================================
# NETWORK
# =========================================================

networks:
  voip-net:
    driver: bridge

volumes:
  pg_data:

