[transport-defaults](!) ; Это шаблон для всех транспортов
type = transport
bind = 0.0.0.0:5060
allow_reload = True

; local_net = 127.0.0.0/8
; local_net = 10.0.0.0/8
; local_net = 172.16.0.0/8
; local_net = 192.168.1.0/24

; Статичное IP ЭТОЙ машинки
external_media_address     = 127.0.0.1
external_signaling_address = 127.0.0.1

[transport-udp](transport-defaults)
protocol = udp

; ========================================================
;               Настройка ENDPOINT
; ========================================================
[endpoint-default](!) ; шаблон endpoint
type = endpoint
transport = transport-udp
disallow = all
allow = ulaw

direct_media=no

rewrite_contact=yes
rtp_symmetric=yes
force_rport=yes

ice_support=no

[100](endpoint-default)
context = from-internal
auth = auth-100
aors = 100

; ========================================================
;                  Настройка Auth
; ========================================================
[auth-default](!)
type = auth
auth_type = userpass

[auth-100](auth-default)
username = 100
password = 100

; ========================================================
;                  Настройка AOR
; ========================================================
[aor-default](!)
type = aor

[100](aor-default)
max_contacts = 1
remove_existing=yes
qualify_frequency=30